sudo: required
dist: trusty

language: node_js
node:
  - 12

if: branch = master AND commit_message =~ ci-build

jobs:
  include:
    - name: "macOS"
      os: osx
      osx_image: "xcode11.3"
      script:
        - electron-builder --publish=always

    - name: "Windows"
      os: osx
      osx_image: "xcode11.3"
      script:
        - electron-builder -w --x64 --ia32 --publish=onTagOrDraft
        - node ./scripts/rename_portable.js
        - electron-builder --windows portable --ia32 --publish=onTagOrDraft

    - name: "Linux"
      os: linux
      script:
        - sudo apt-get install rpm
        - electron-builder --publish=onTagOrDraft

cache:
  directories:
    - node_modules

install:
  - npm install

notifications:
  email: false